name: Build Kivy APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/upload-artifact@v4


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk git unzip
          pip3 install --upgrade Cython buildozer
          pip3 install kivy kivymd pandas

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/^requirements = python3,kivy$/requirements = python3,kivy,kivymd,pandas/' buildozer.spec
          sed -i 's/^android.permissions = INTERNET$/android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/' buildozer.spec
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
